# This workflow removes the deployment of pull request from Heroku https://grid-optimizer-pr-xxx.herokuapp.com/

name: Delete PR Deploy @ Heroku 

# Controls when the action will run. 
on:
  pull_request:
    types: [closed]


jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: "${{ github.token }}"
          environment: "PR #${{ github.event.pull_request.number }} Review"
      - name: Login @ Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "grid-optimizer-pr-${{ github.event.pull_request.number }}"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - name: Destroy App @ Heroku
        run: "heroku apps:destroy --app=grid-optimizer-pr-${{ github.event.pull_request.number }} --confirm=confirm" 
   
